### ISSUE TITLE
xiaomi_clean_zone not working

### ISSUE THREAD

**Issue by FeromonDE** [nqkdev/home-assistant-vacuum-styj02ym#19]
Hallo,

why this script did not work
vacuum_set_zone:
  sequence:
  - data:
      repeats: 1
      zone: [[-0.2222,0.3843,-0.2222,-1.8565],[1.8241,-1.8565,1.8241,0.3843]]
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.xiaomi_clean_zone
  mode: single
  alias: Mi Robot set zone

I have coordinates from vevs Mi Home app.

**Comment by KochC** [comment]
I have the same issue. But if I send coordinates in Meters, like
```
[[0,0,1,1]]
```
the robot really tries to clean a square of one meter by one meter where `0,0` is his home.
Unfortunately I get an `localisation` error after a few seconds. But I can see the area to clean in the Xiaomi App.

**Comment by Su4oNoK** [comment]
this is work for me
script in HA

```
sc_clean_living_room:
  alias: "Уборка в комнате"
  sequence:
  - service: vacuum.xiaomi_clean_zone
    data:
      entity_id: vacuum.kefirchik
      zone: [[-0.8, -5, 3.2, 0.5]]
      repeats: 1
```
