### ISSUE TITLE
Command for cancel vacuuming and return home

### ISSUE THREAD

**Issue by jeppii** [nqkdev/home-assistant-vacuum-styj02ym#59]
Is there any way to cancel the vacuuming and send it back home? I could't find any in the service.yaml about this. Thanks!

**Comment by Su4oNoK** [comment]
I'm use this UI  - https://github.com/denysdovhan/vacuum-card
and add script for clean room (zone clean)

```
sc_clean_living_room:
  alias: "Уборка в комнате"
  sequence:
  - service: vacuum.xiaomi_clean_zone
    data:
      entity_id: vacuum.kefirchik
      zone: [[-0.8, -5, 3.2, 0.5]]
      repeats: 1
```
